### ISSUE TITLE
Chef/AttributeKeys throws exceptions with methods on node attributes

### ISSUE THREAD

**Issue by tas50** [poise/rubocop-chef#8]
Here's a distilled failure snippet:

node['os_version'].to_f

```
❰tsmith❙~/dev/chef-cookbooks/test/recipes(git✱master)❱✔≻ cookstyle -a . -d                                                   19:37:46
For /Users/tsmith/dev/chef-cookbooks/test/recipes: configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/default.yml
Inheriting configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/upstream.yml
Inheriting configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/enabled.yml
Inheriting configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/disabled.yml
Inheriting configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/disable_all.yml
Inheriting configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/cookstyle_base.yml
Inheriting configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/cookstyle.yml
configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-chef-1.0.0.pre/config/default.yml
configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-chef-1.0.0.pre/config/default.yml
Default configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/default.yml
Inheriting configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/upstream.yml
Inheriting configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/enabled.yml
Inheriting configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/disabled.yml
Inheriting configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/disable_all.yml
Inheriting configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/cookstyle_base.yml
Inheriting configuration from /Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/config/cookstyle.yml
Inspecting 1 file
Scanning /Users/tsmith/dev/chef-cookbooks/test/recipes/default.rb
An error occurred while Chef/AttributeKeys cop was inspecting /Users/tsmith/dev/chef-cookbooks/test/recipes/default.rb:7:0.
undefined method `to_sym' for nil:NilClass
Did you mean?  to_s
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/mixin/configurable_enforced_style.rb:66:in `style'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-chef-1.0.0.pre/lib/rubocop/cop/chef/attribute_keys.rb:71:in `on_node_attribute_access'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-chef-1.0.0.pre/lib/rubocop/cop/chef/attribute_keys.rb:64:in `on_send'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:43:in `block (2 levels) in on_send'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:102:in `with_cop_error_handling'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:42:in `block in on_send'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:41:in `each'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:41:in `on_send'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/ast/traversal.rb:101:in `block in on_send'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/ast/traversal.rb:99:in `each'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/ast/traversal.rb:99:in `each_with_index'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/ast/traversal.rb:99:in `on_send'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:47:in `on_send'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/ast/traversal.rb:12:in `walk'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:60:in `investigate'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/team.rb:121:in `investigate'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/team.rb:101:in `offenses'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/team.rb:51:in `inspect_file'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:248:in `inspect_file'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:195:in `block in do_inspection_loop'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:227:in `block in iterate_until_no_changes'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:220:in `loop'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:220:in `iterate_until_no_changes'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:191:in `do_inspection_loop'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:101:in `block in file_offenses'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:111:in `file_offense_cache'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:99:in `file_offenses'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:90:in `process_file'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:68:in `block in each_inspected_file'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:65:in `each'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:65:in `reduce'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:65:in `each_inspected_file'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:36:in `run'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cli.rb:72:in `execute_runner'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cli.rb:27:in `run'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/bin/rubocop:13:in `block in <top (required)>'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/bin/rubocop:12:in `<top (required)>'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/bin/cookstyle:13:in `load'
/Users/tsmith/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cookstyle-1.3.0/bin/cookstyle:13:in `<top (required)>'
/Users/tsmith/.rbenv/versions/2.3.3/bin/cookstyle:22:in `load'
/Users/tsmith/.rbenv/versions/2.3.3/bin/cookstyle:22:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Chef/AttributeKeys cop was inspecting /Users/tsmith/dev/chef-cookbooks/test/recipes/default.rb:7:0.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.47.1 (using Parser 2.4.0.0, running on ruby 2.3.3 x86_64-darwin16)
```

**Comment by tas50** [comment]
This was actually a config issue
